version: "3"

services:
  backend:
    build: ./node.js
    links:
         - redis
    ports:
         - "8080:8080"
    volumes:
         - ./node.js:/src
  frontend:
    build: ./frontend
    ports:
         - "3000:3000"
    volumes:
         - ./frontend:/src
  redis:
     image: redis:latest
     ports:
          - 6379:6379
